# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linux test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout github repo including lfs files
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        channels: conda-forge
        activate-environment: rsqsim-python-tools
        environment-file: environment.yml
        use-mamba: true
        auto-activate-base: false

    - name: Install test dependencies
      run: |
        mamba install flake8 pytest

    - name: Run lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names (data directory excluded)
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=data
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      run: |
        pytest
